name: Daily Octopus Agile Slack Alert
on:
  #schedule:
    # UTC 15:10 = 英国夏令时(BST) 下午 16:10
  #  - cron: '10 15 * * *'
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          OCTOPUS_PRODUCT_CODE: "AGILE-24-10-01"
          OCTOPUS_REGION_CODE: "C"
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
          OCTOPUS_MPAN: ${{ secrets.OCTOPUS_MPAN }}
          OCTOPUS_METER_SERIAL: ${{ secrets.OCTOPUS_METER_SERIAL }}
        run: python main.py
